#homework3:

age_input=input("how old are you?:")

age=int(age_input)

print("in 5 years you will be")

print(age+5)

print("years old")

#homework4:

#ცვლადებისგანსაზღვრა
varible_1="Python is the best"
varible_2=2100
varible_3=3.124
varible_4="string"
varible_5=69
varible_6=9.655
varible_7="hello Goa"
varible_8=150
varible_9=2.677
varible_10="goa is the best"
varible_11=-123
varible_12=0.1
varible_13="hello world"
varible_14=254
varible_15=6.1
varible_16="NO JUNK FOOD!"
varible_17=456
varible_18=1.7
varible_19="Nature"
varible_20=100

#თითოეულიცვლადისტიპისგანსაზღვრადადაბეჭვდა
print(type(varible_1))
print(type(varible_2))
print(type(varible_3))
print(type(varible_4))
print(type(varible_5))
print(type(varible_6))
print(type(varible_7))
print(type(varible_8))
print(type(varible_9))
print(type(varible_10))
print(type(varible_11))
print(type(varible_12))
print(type(varible_13))
print(type(varible_14))
print(type(varible_15))
print(type(varible_16))
print(type(varible_17))
print(type(varible_18))
print(type(varible_19))
print(type(varible_20))