for  i in range(1, 5):
    print(i)

for  i in range(10, 21):
    print(i)

for  i in range(2, 8):
    print(i)

for  i in range(3, 5):
    print(i)

for  i in range(30, 51):
    print(i)




for  i in range(20):
    print("Lazare")

for  i in range(30):
    print("Chikovani")

for  i in range(50):
    print("11")

for i in range(10):
    name = input("Enter your name: ")
    print(f"Enter your name: ")
