name = input("what is your  name?: ")
print(name)
#hommework 2
name = input("what is your full name?: ")
print(name)
print("hello giorgi i know it is your bithday so happy bithrday")
#homework 3
favorite = input("whats your favorite animal,color,car and who is your favorite actor?: ")
print(favorite)
#homework 4
#input პროგრამირებაში არის  ყველა ის ინფორმაცია რომელიც შედის კომპიუტერში! (ის ქართულად შეყვანს ნიშანვს!)
#output პროგრამირებაში არის  შედეგი რაც გამოდის საბოლოოდ! (ის ქართულად გამოყვანას ნიშნავს!)
#"Concatenation" არის ორი ტიპის ან მეტი ობიექტების ერთმანეთში შეერთება პროგრამირების მეთოდი! (ის ქართულად შეერტებას  ნიშნავს!)