print(5 > 10)
print(1 > 11)
print(10 > 32)
print(100 > 200)

print(100 >= 20)
print(2333 >= 20332)
print(247 >= 36)
print(28 >= 28)

print(362 < 364)
print(363 < 37)
print(3434 < 374)
print(438 < 79)

print(733 <= 374)
print(63426 <= 346)
print(3673 <= 364)
print(3637 <= 37)

print(37467 != 374)
print(83483 != 83)
print(3344 != 3434)
print(31323 !=  333)

print(100 == 28)
print(100000 == 23)
print(10 == 11)
print(10 == 10)

age = input('how old are you?:')
age_2 = input("how old is your couson?:")

print(age < age_2)
print(age > age_2)
print(age <= age_2)
print(age >= age_2)
print(age != age_2)
print(age == age_2)