large_list = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20}

example_1= large_list[5:]   
example_2 = large_list[10:]    
example_3 = large_list[15:]    
example_4 = large_list[:5]    
example_5 = large_list[:10]    


example_1 = large_list[5:10]  
example_2 = large_list[10:15] 
example_3 = large_list[:7]    
example_4 = large_list[8:12] 
example_5 = large_list[3:18]  


example_1 = large_list[:7:2]   
example_2 = large_list[1:4:3] 
example_3 = large_list[4:15:2]
example_4 = large_list[:2:1]  
example_5 = large_list[3:15:3] 


print(example_1)
print(example_2)
print(example_3)
print(example_4)
print(example_5)


print(example_1)
print(example_2)
print(example_3)
print(example_4)
print(example_5)

print(example_1)
print(example_2)
print(example_3)
print(example_4)
print(example_5)
