#homework 2

# String არის ტექსტი. 
# ის შეიძლება იყოს სიტყვები, ფრაზები ან ნებისმიერი ტექსტი, რომელიც ჩვენ გვინდა.
string_example = "გამარჯობა, გოა!"

# Integer არის მთელი რიცხვი.
# მას არ აქვს წერტილოვანი ნაწილი.
integer_example = 49

# Float არის წერტილოვანი რიცხვი.
# მას აქვს წერტილოვანი ნაწილი.
float_example = 3.19

#homework 3

# ინფორმაციის დაყოფა მონაცემთა ტიპებად გვჭირდება, 
# რომ უკეთ გავიგოთ და დავამუშავოთ ეს ინფორმაცია.
# მაგალითად, თუ ჩვენ გვინდა ტექსტის დამუშავება, 
# გამოვიყენებთ string-ს. თუ გვინდა რიცხვის დამატება, გამოვიყენებთ integer-ს ან float-ს.

#homework 4


print("Iron" + "Man")  

print("Hello" + "Goa") 

print("Season" + "7")

print("Hi" + " " + "nika")

print("Data " + "types") 

print("Game: " + "kahhot")  

print("nika" + " " + "keshelava")  

print("1000" + "2") 

print("blue" + " " + "Ball")

print("Star" + "Wars")  

print("watermelon" + " " + "Slice")  

print("Good" + " " + "game")  

print("saterday" + " " + "5 am")  

print("Football" + " " + "Goalkeeper")  

print("yellow" + " " + "Circle")  

print("we are at" + " " + "Home")  

print("Water" +  "melon")  

print("Version" + " " + "10.0") 

print("Smart" + " " + "man")  

print("smart"+ " " + "women") 

#homework 5

user_input = input("გთხოვთ, შეიყვანოთ ინფორმაცია: ")

print("თქვენ შეიყვანეთ: " + user_input)
